"""
Meeting transcript summarization for Meetly.

This module takes a finalized meeting transcript and uses the
existing Meetly LLM client to generate a concise meeting summary.

Responsibilities:
    - Accept finalized transcript text.
    - Build the summary prompt.
    - Call the existing LLM infrastructure.
    - Return the generated summary.

This module does not:
    - record audio
    - transcribe audio
    - perform diarization
    - assemble transcript chunks
    - create or manage the LLM HTTP client
"""

from __future__ import annotations

from meetly.llm import LLMClient, SUMMARY_PROMPT, SYSTEM_PROMPT


class MeetingSummarizer:
    """
    Generates summaries from finalized meeting transcripts.
    """

    def __init__(
        self,
        llm: LLMClient,
    ) -> None:
        """
        Initialize the summarizer.

        Args:
            llm:
                Existing Meetly LLM client.
        """

        self._llm = llm

    async def summarize(
        self,
        transcript: str,
    ) -> str:
        """
        Generate a summary for a finalized meeting transcript.

        Args:
            transcript:
                Complete finalized meeting transcript as plain text.

        Returns:
            Concise meeting summary generated by the LLM.

        Raises:
            ValueError:
                If the transcript is empty.
        """

        if not isinstance(transcript, str):
            raise TypeError(
                "transcript must be a string."
            )

        transcript = transcript.strip()

        if not transcript:
            raise ValueError(
                "Cannot summarize an empty transcript."
            )

        user_prompt = SUMMARY_PROMPT.format(
            transcript=transcript
        )

        return await self._llm.complete(
            system_prompt=SYSTEM_PROMPT,
            user_prompt=user_prompt,
        )


__all__ = [
    "MeetingSummarizer",
]